In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
Generating the data for KNN
- Generate values for class 0
    - Generate x1 values within the range 0 to 50
    - Generate x2 values within range 1 to 50
    - Create a 2d array with x1 values as 0 th element and x2 values as 1st element,3rd value is zero
- Generate value for class 1
    -Generate x1 values within the range 50 to 100
    -Generate x2 values within range 1 to 50
    - create a 2d array with x1 values as 0 th element and x2 values as 1st element,3rd element is one
- Create a 2d array which consists both classes data
- create a DataFrame from this data with added Y column

In [11]:
import numpy as np
np.random.seed(10)
x1 = np.random.randint(0,50,50)
x2 = np.random.randint(1,50,50)
x3 = np.expand_dims(x1,1)
x4 = np.expand_dims(x2,1)
x5 = np.expand_dims(np.ones(50,dtype=int),1)
d = np.hstack((x3,x4,x5))
x1,x2

(array([ 9, 36, 15,  0, 49, 28, 25, 29, 48, 29, 49,  8,  9,  0, 42, 40, 36,
        16, 36, 47, 11, 24, 43, 33,  8, 36, 14, 49, 13,  5, 13, 25, 13, 28,
        22, 30, 30, 25, 12,  1, 31, 36, 27, 18, 29, 13, 22, 23, 30, 11]),
 array([29, 11, 25, 10, 16, 19, 17,  8, 25, 12, 18, 47,  8, 12, 29, 34, 21,
        33, 25, 45,  6,  5,  8, 25, 25, 45, 35, 41, 16, 14, 25, 16,  7, 22,
        43, 23, 12, 49, 13, 29, 33, 16, 45, 41, 43, 46, 44, 34, 46, 41]))

In [4]:
np.hstack((x1,x2))

array([ 9, 36, 15,  0, 49, 28, 25, 29, 48, 29, 49,  8,  9,  0, 42, 40, 36,
       16, 36, 47, 11, 24, 43, 33,  8, 36, 14, 49, 13,  5, 13, 25, 13, 28,
       22, 30, 30, 25, 12,  1, 31, 36, 27, 18, 29, 13, 22, 23, 30, 11, 29,
       11, 25, 10, 16, 19, 17,  8, 25, 12, 18, 47,  8, 12, 29, 34, 21, 33,
       25, 45,  6,  5,  8, 25, 25, 45, 35, 41, 16, 14, 25, 16,  7, 22, 43,
       23, 12, 49, 13, 29, 33, 16, 45, 41, 43, 46, 44, 34, 46, 41])

In [5]:
np.vstack((x1,x2))

array([[ 9, 36, 15,  0, 49, 28, 25, 29, 48, 29, 49,  8,  9,  0, 42, 40,
        36, 16, 36, 47, 11, 24, 43, 33,  8, 36, 14, 49, 13,  5, 13, 25,
        13, 28, 22, 30, 30, 25, 12,  1, 31, 36, 27, 18, 29, 13, 22, 23,
        30, 11],
       [29, 11, 25, 10, 16, 19, 17,  8, 25, 12, 18, 47,  8, 12, 29, 34,
        21, 33, 25, 45,  6,  5,  8, 25, 25, 45, 35, 41, 16, 14, 25, 16,
         7, 22, 43, 23, 12, 49, 13, 29, 33, 16, 45, 41, 43, 46, 44, 34,
        46, 41]])

In [7]:
x3 = np.expand_dims(x1,1)
x4 = np.expand_dims(x2,1)
x3,x4

(array([[ 9],
        [36],
        [15],
        [ 0],
        [49],
        [28],
        [25],
        [29],
        [48],
        [29],
        [49],
        [ 8],
        [ 9],
        [ 0],
        [42],
        [40],
        [36],
        [16],
        [36],
        [47],
        [11],
        [24],
        [43],
        [33],
        [ 8],
        [36],
        [14],
        [49],
        [13],
        [ 5],
        [13],
        [25],
        [13],
        [28],
        [22],
        [30],
        [30],
        [25],
        [12],
        [ 1],
        [31],
        [36],
        [27],
        [18],
        [29],
        [13],
        [22],
        [23],
        [30],
        [11]]), array([[29],
        [11],
        [25],
        [10],
        [16],
        [19],
        [17],
        [ 8],
        [25],
        [12],
        [18],
        [47],
        [ 8],
        [12],
        [29],
        [34],
        [21],
        [33],
        [25],
        [45],
        [ 6],
     

In [9]:
np.hstack((x3,x4))

array([[ 9, 29],
       [36, 11],
       [15, 25],
       [ 0, 10],
       [49, 16],
       [28, 19],
       [25, 17],
       [29,  8],
       [48, 25],
       [29, 12],
       [49, 18],
       [ 8, 47],
       [ 9,  8],
       [ 0, 12],
       [42, 29],
       [40, 34],
       [36, 21],
       [16, 33],
       [36, 25],
       [47, 45],
       [11,  6],
       [24,  5],
       [43,  8],
       [33, 25],
       [ 8, 25],
       [36, 45],
       [14, 35],
       [49, 41],
       [13, 16],
       [ 5, 14],
       [13, 25],
       [25, 16],
       [13,  7],
       [28, 22],
       [22, 43],
       [30, 23],
       [30, 12],
       [25, 49],
       [12, 13],
       [ 1, 29],
       [31, 33],
       [36, 16],
       [27, 45],
       [18, 41],
       [29, 43],
       [13, 46],
       [22, 44],
       [23, 34],
       [30, 46],
       [11, 41]])

In [19]:
import matplotlib.pyplot as plt
plt.scatter(df['x1'][:50],df['x2'][:50],color='r')


NameError: name 'df' is not defined

In [17]:
def knearest_points(p,d,k):
    distance = []
    for row in d:
        distance.append(Eucledian_distance(row,p))
    distance = np.array(distances)
    return d[distance

In [18]:
plt.scatter(df['x1'][:50],df['x2'][:50],color='r')
plt.scatter(df['x1'][:50],df['x2'][:50],color='g')
plt.plot(5,34,'bo')
plt.scatter(near_4[:,0],near_4[:,1],color='y')

NameError: name 'df' is not defined

In [21]:
import pandas as pd
df = pd.Dataframe([x1,x2])

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [1]:
import numpy as np
np.array(target)

NameError: name 'target' is not defined

In [2]:
version(openCV)

NameError: name 'version' is not defined

In [7]:
import cv2
cv2.__version__

ModuleNotFoundError: No module named 'cv2'