### Sin funcations

In [22]:
import math
print ("asin(0.640)")
math.asin(0.64)

SyntaxError: invalid syntax (<ipython-input-22-4b7e141886c7>, line 2)

In [23]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [25]:
np.__version__

'1.16.5'

In [ ]:
from numpy import array

In [27]:
a = np.array(range(5,10))
print(a)
print(type(a))

[5 6 7 8 9]
<class 'numpy.ndarray'>


In [31]:
a = np.array([1,2,3,7,312]),dtype=np.int8)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.itemsize)
print(a.ndim)
print(a.nbytes)

(5,)
int32
5
4
1
20


In [36]:
a2 = np.array([[1,2,5],[3,4,5],[6,7,9]])
print(a2)

[[1 2 5]
 [3 4 5]
 [6 7 9]]


In [37]:
print(a2.shape)
print(a2.dtype)
print(a2.size)
print(a2.itemsize)
print(a2.ndim)
print(a2.nbytes)

(3, 3)
int32
9
4
2
36


In [40]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [43]:
a = np.array([1,2,3,7,(2**32)+1])
print(a.dtype)

int64


In [44]:
np.ones((2,3),bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

## initializing Arrays
- zeros
- ones
- full
- eye
- diag

In [49]:
np.zeros((2,3),bool)

array([[False, False, False],
       [False, False, False]])

np.full((2,3),bool)

In [53]:
np.diag((2,3),bool)

TypeError: bad operand type for abs(): 'type'

## Creating arrays in a range
- arange
- linespace

In [62]:
print(np.arange(0.5,10,0.7))

[0.5 1.2 1.9 2.6 3.3 4.  4.7 5.4 6.1 6.8 7.5 8.2 8.9 9.6]


In [63]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Mathematical Operation

In [66]:
import numpy as np
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [72]:
a = np.arange(5)
b = np.ones(5)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a%b)
print(a/b)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]
[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0.]
[0. 1. 2. 3. 4.]


In [77]:
print(a+2)
print(a-2)
print(a*2)
print(a%2)
print(a//2)


[2 3 4 5 6]
[-2 -1  0  1  2]
[0 2 4 6 8]
[0 1 0 1 0]
[0 0 1 1 2]


# Random

In [80]:
np.random.randint(99,100)

99

In [83]:
np.random.randint(100,size=(5,2))

array([[ 8, 30],
       [17,  2],
       [47, 36],
       [63, 46],
       [11, 35]])

In [84]:
np.random.random((2,3))

array([[0.97378715, 0.50064179, 0.55234566],
       [0.29083306, 0.7538    , 0.57169684]])

In [86]:
n = np.arange(10)
np.random.shuffle(n)
print(n)

[4 1 5 0 7 2 3 6 9 8]


In [92]:
n = np.arange(25)
n.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [94]:
n.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [95]:
n.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [100]:
z = np.arange(20)
z.resize((13,2))

In [104]:
np.expand_dims(a2,0)

array([[[1, 2, 5],
        [3, 4, 5],
        [6, 7, 9]]])

In [106]:
np.expand_dims(a2,1).shape

(3, 1, 3)

In [108]:
a2[2,2]

9

In [ ]:
a2[[1,3,2]]